name: Build docs artifact for PR

on:
  pull_request:
    paths:
      # We generate documentation for boefje, bytes, mula and octopoes
      # from code so the workflow should also depend on it.
      - "boefje/**"
      - "bytes/**"
      - "docs/**"
      - "mula/**"
      - "octopoes/**"
      - "requirements.txt"
      - ".github/workflows/build_docs_on_pr.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-artifact:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.13
          cache: "pip" # caching pip dependencies

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Compile static HTML
        run: make docs

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "github-pages-no-deploy"
          path: "docs/_build"
